project:
  type: website

website:
  title: "priorDB"
  navbar:
    left:
      - text: "Linear regression"
        menu:
          - linear_regression_overview.qmd
          - linear_regression_comparison.qmd
          - scaled_default.qmd
          - l1_ball.qmd
          - r2d2.qmd
          - rhs.qmd
      - text: "Hierarchical linear regression"
        menu:
          - hierarchical_regression_overview.qmd
          - r2d2m2.qmd
      - text: "Logistic regression"
        menu:
          - logistic_regression_overview.qmd
          - logistic_default.qmd
      - text: "Autoregression"
        menu:
          - autoregression_overview.qmd
          - autoregression_comparison.qmd
          - minnesota.qmd
          - arr2.qmd
      - text: "Negative binomial"
        menu:
          - negative_binomial_overview.qmd
          - negative_binomial_shape.qmd
      - text: "Conway-Maxwell-Poisson"
        menu:
          - cmp_overview.qmd
          - cmp_conjugate.qmd

          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true


filters:
  - include-code-files
