project:
  type: website
  execute-dir: project
website:
  title: "priorDB"
  sidebar:
    collapse-level: 1
    contents:
      - section: "(Generalised) linear models"
        contents:
          - section: "Normal (Gaussian)"
            contents:
              - gen_linear_regression/linear_regression_overview.qmd
              - gen_linear_regression/r2d2.qmd
              - gen_linear_regression/rhs.qmd
              - gen_linear_regression/l1_ball.qmd
          - section: "Bernoulli (logistic)"
            contents:
              - gen_linear_regression/bernoulli_overview.qmd
          - section: "Student-t"
            contents:
              - gen_linear_regression/student_t.qmd
          - section: "Negative binomial"
            contents:
              - gen_linear_regression/negative_binomial_overview.qmd
              - gen_linear_regression/negative_binomial_shape.qmd
          - section: "Conway-Maxwell-Poisson"
            contents:
              - gen_linear_regression/cmp_overview.qmd
              - gen_linear_regression/cmp_conjugate.qmd
              
      - section: "Autoregression"
        contents:
          - autoregression/autoregression_overview.qmd
          - autoregression/arr2.qmd
          - autoregression/minnesota.qmd

      - section: "Hierarchical regression"
        contents:
          - hierarchical_regression/hierarchical_regression_overview.qmd
          - hierarchical_regression/r2d2m2.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true


filters:
  - include-code-files


bibliography: references.bib

