project:
  type: website
  execute-dir: project
website:
  title: "priorDB"
  sidebar:
    contents:
      - section: "(Generalised) linear regression"
        contents:
          - section: "Normal (Gaussian)"
            contents:
              - title: "Overview"
                file: linear_regression/linear_regression_overview.qmd
              - linear_regression/r2d2.qmd
              - linear_regression/rhs.qmd
              - linear_regression/l1_ball.qmd
          - section: "Bernoulli (logistic)"
            contents:
          - section: "Student-t"
          - section: "Negative binomial"
            contents:
              - title: "Overview"
                file: negative_binomial_overview.qmd
              - negative_binomial_shape.qmd
      - section: "Autoregression"
        contents:
          - autoregression/autoregression_overview.qmd
          - autoregression/arr2.qmd
          - autoregression/minnesota.qmd

      - section: "Hierarchical regression"
        contents:
          - hierarchical_regression/hierarchical_regression_overview.qmd
          - hierarchical_regression/r2d2m2.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true


filters:
  - include-code-files


bibliography: references.bib

