project:
  type: website
  execute-dir: project
website:
  title: "priorDB"
  sidebar:
    collapse-level: 1
    contents:
      - section: "Regression"
        contents:
          - gen_linear_regression/gen_linear_regression_overview.qmd
          - section: "Continuous outcome"
            contents:
              - section: "Unbounded"
                contents:
                  - gen_linear_regression/normal.qmd
                  - gen_linear_regression/student_t.qmd
              - section: "Bounded"
                contents:
                  - gen_linear_regression/beta.qmd
          - section: "Binary outcome"
            contents:
            - gen_linear_regression/bernoulli_logit.qmd
          - section: "Discrete outcome"
            contents:
              - section: "Unbounded"
              - section: "Bounded"
                contents:
                  - gen_linear_regression/poisson.qmd
                  - gen_linear_regression/negative_binomial.qmd
                  - gen_linear_regression/binomial.qmd
                  - gen_linear_regression/categorical.qmd
                  - gen_linear_regression/ordered.qmd
          - section: "Sparsity priors"
            contents:
            - gen_linear_regression/r2d2.qmd
            - gen_linear_regression/rhs.qmd
            - gen_linear_regression/l1_ball.qmd
      - section: "Autoregression"
        contents:
          - autoregression/autoregression_overview.qmd
          - autoregression/arr2.qmd
          - autoregression/minnesota.qmd

      - section: "Hierarchical regression"
        contents:
          - hierarchical_regression/hierarchical_regression_overview.qmd
          - hierarchical_regression/r2d2m2.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true


filters:
  - include-code-files


bibliography: references.bib
