project:
  type: website
  execute-dir: project
website:
  title: "priorDB"
  sidebar:
    collapse-level: 1
    contents:
      - section: "(Generalised) linear models"
        contents:
          - gen_linear_regression/gen_linear_regression_overview.qmd
          - section: "Predictor weights"
            contents:
            - gen_linear_regression/r2d2.qmd
            - gen_linear_regression/rhs.qmd
            - gen_linear_regression/l1_ball.qmd
          - section: "Unbounded continuous outcomes"
            contents:
            - gen_linear_regression/normal_overview.qmd
            - gen_linear_regression/student_t.qmd
          - section: "Binary outcome"
            contents:
            - gen_linear_regression/bernoulli_overview.qmd
          - section: "Count outcome"
            contents:
            - gen_linear_regression/poisson_overview.qmd
            - gen_linear_regression/negative_binomial_overview.qmd
            - gen_linear_regression/cmp_overview.qmd    
      - section: "Autoregression"
        contents:
          - autoregression/autoregression_overview.qmd
          - autoregression/arr2.qmd
          - autoregression/minnesota.qmd

      - section: "Hierarchical regression"
        contents:
          - hierarchical_regression/hierarchical_regression_overview.qmd
          - hierarchical_regression/r2d2m2.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true


filters:
  - include-code-files


bibliography: references.bib
