project:
  type: website
  execute-dir: project

website:
  title: "priorDB"
  description: "A collaborative database of models and their priors" 
  site-url: https://n-kall.github.io/priorDB/
  repo-url: https://github.com/n-kall/priorDB
  repo-actions: [source, issue]
  page-navigation: true
  sidebar:
    collapse-level: 1
    contents:
      - text: "Models"
      - section: "Regression"
        contents:
          - text: "Overview"
            href: gen_linear_regression/gen_linear_regression_overview.qmd
          - section: "Continuous outcome"
            contents:
              - section: "Unbounded"
                contents:
                  - gen_linear_regression/normal.qmd
                  - gen_linear_regression/student_t.qmd
              - section: "Bounded"
                contents:
                  - gen_linear_regression/beta.qmd
          - section: "Discrete outcome"
            contents:
              - section: "Binary"
                contents:
                - gen_linear_regression/bernoulli_logit.qmd
              - section: "Count"
                contents:
                  - gen_linear_regression/poisson.qmd
                  - gen_linear_regression/negative_binomial.qmd
                  - gen_linear_regression/binomial.qmd
              - section: "Categorical"
                contents:
                  - gen_linear_regression/categorical.qmd
              - section: "Ordered"
                contents:
                  - gen_linear_regression/ordinal.qmd
          - section: "Sparsity priors"
            contents:
            - gen_linear_regression/gr2.qmd
            - gen_linear_regression/r2d2.qmd
            - gen_linear_regression/rhs.qmd
            - gen_linear_regression/l1_ball.qmd
            - gen_linear_regression/becca.qmd
      - section: "Autoregression"
        contents:
          - text: "Overview"
            href: autoregression/autoregression_overview.qmd
          - autoregression/arr2.qmd
          - autoregression/minnesota.qmd
      - section: "Hierarchical regression"
        contents:
          - text: "Overview"
            href: hierarchical_regression/hierarchical_regression_overview.qmd
          - hierarchical_regression/r2d2m2.qmd
      - text: "<br>"

      - text: "External resources"
      - text: "Software Tools"
        href: tools.qmd
      - text: "Stan prior guide"
        href: Stan_prior_choice.qmd        
      - text: "<br>"
      - text: "Contributors"
        href: contributors.md


format:
  html:
    css: styles.css
    toc: true
    code-fold: true
    template-partials:
      - title-block.html  ## remove list of authors from the header of all pages
    include-in-header:
      - text: |
          <meta name="google-site-verification" content="JBA8wBXkShP3bdTtVwzNv-fM1iTo8HZ0hkLK5ZbRgV8" /> 
           
theme:
  light: cosmo
  dark: darkly

filters:
  - include-code-files

bibliography: references.bib

author:
  - name: Noa Kallioinen
    affiliation: Aalto University
    orcid: 0000-0003-1586-8382 
google-scholar: true
