---
title: Beta model
---

## Description

Beta regression is used for outcomes on the [0, 1] interval.


## Definition

For continuous outcome $y$ bounded [0, 1] and predictors $x$, the model is:

$$
\begin{align}
y_i \sim \text{beta}(\text{logit}^{-1}(\mu_i), \kappa) \\
\mu_i = \alpha_{\mu} + \beta_{\mu} \cdot x \\
\end{align}
$$

## Parameters needing priors

- $\alpha$ (intercept)
- $\beta$ (predictor weights)
- $\kappa$ (concentration parameter)

The larger the value of $\kappa$, the more concentrated the distribution is around the mean. This parameter is also named the precision parameter or the sample size. Greek letter $\nu$ and $\phi$ are also commonly used to refer to this parameter.

## Prior for $\kappa$

For  weakly informative prior we can use a gamma distribution with low probability mass on very small values of $\kappa$, such priors disfavors u-shaped beta distributions which are generally less common in real-world data. For instance we could choose $\text{gamma{(4, 0.1)$ as discussed by [Solomon Kurz](https://solomonkurz.netlify.app/blog/2023-06-25-causal-inference-with-beta-regression/), wich place most of the prior mass on the double-digit range with long right tail allowing for greater concentrations if needed.


## See also

- [Distribution explorer](https://distribution-explorer.github.io/continuous/beta.html)
- [PreliZ](https://preliz.readthedocs.io/en/latest/examples/gallery/beta.html)
- [Stan Functions Reference](https://mc-stan.org/docs/functions-reference/continuous_distributions_on_0_1.html#beta-distribution)
- [rstanarm manual](https://mc-stan.org/rstanarm/articles/betareg.html)
- [bambi manual](https://bambinos.github.io/bambi/notebooks/beta_regression.html)
- [Andrew Wheiss' blog](https://www.andrewheiss.com/blog/2021/11/08/beta-regression-guide/)