---
title: Negative-binomial model
---

## Description

The negative-binomial model is a model of counts that allows for
overdispersion.

## Definition

For discrete positive outcome $y$ and predictors $x$, the model is:

$$
\begin{align}
y_i \sim \text{NegBinomial}(\exp{(\eta_i)}, \phi) \\
\eta_i = \alpha + \beta \cdot x_i
\end{align}
$$

## Parameters needing priors

- $\alpha$ (intercept)
- $\beta$ (predictor weights)
- $\phi$ (overdispersion parameter)

## Prior for $\phi$

### Weakly informative inverse gamma prior

@vehtariDefaultPriorNegativebinomial2024 suggested an inverse gamma prior as an approximation of the penalized complexity prior:

$\phi \sim \text{InvGamma}(0.4, 0.3)$

### Penalized complexity prior

@simpsonPenalisingModelComponent2017 suggested a penalized complexity prior

## See also


- [Distribution explorer](https://distribution-explorer.github.io/discrete/negative_binomial.html)
- [PreliZ](https://preliz.readthedocs.io/en/latest/examples/gallery/negativebinomial.html)
- [Aki Vehtari's case study](https://users.aalto.fi/~ave/modelselection/roaches.html#3_Negative_binomial_model)
- [Stan Functions Reference](https://mc-stan.org/docs/functions-reference/unbounded_discrete_distributions.
html#negative-binomial-distribution)
- [bambi example](https://bambinos.github.io/bambi/notebooks/negative_binomial.html)
