---
title: Normal model
---

## Description

Linear regression with normally distributed residuals.

## Definition

For continuous unbounded outcome $y$ and predictors $x$, the model is:

$$
\begin{align}
y_i \sim \text{normal}(\eta_i, \sigma) \\
\eta_i = \alpha + \beta \cdot x_i
\end{align}
$$

## Parameters needing priors

- $\alpha$ (intercept)
- $\beta$ (predictor weights)
- $\sigma$ (residual standard deviation)

## Prior for $\alpha$

### Weakly informative data-adaptive prior

@gelmanRegressionOtherStories2020 Chapter 9

Centered intercept (expected value of $y$ when predictors are set to mean values of observed data)

$$
\begin{align}
\alpha_{\text{centered}} \sim \text{normal}(\text{mean}(y), 2.5 \text{SD}(y)) \\
\end{align}
$$


## Prior for $\beta$

### Weakly informative data-adaptive normal prior

@gelmanRegressionOtherStories2020 Chapter 9 describes a data-adaptive normal prior

$$
\begin{align}
\beta_k \sim \text{normal}(0, 2.5 \text{SD}(y)/\text{SD}(x_k)).
\end{align}
$$

## Prior for $\sigma$

### Weakly informative data-adaptive exponential prior

@gelmanRegressionOtherStories2020 Chapter 9 describes a data-adaptive exponential prior

$$
\sigma \sim \text{exponential}(1/\text{SD}(y))
$$

## See also

- [Distribution explorer](https://distribution-explorer.github.io/continuous/normal.html)
- [PreliZ](https://preliz.readthedocs.io/en/latest/examples/gallery/normal.html)
- [Stan manual](https://mc-stan.org/docs/functions-reference/unbounded_continuous_distributions.html#normal-distribution)
- [bambi example](https://bambinos.github.io/bambi/notebooks/ESCS_multiple_regression.html)
